from __future__ import annotations

from typing import Any, Iterable, Protocol


class Row(Protocol):
    ...


class Cursor(Protocol):
    rowcount: int

    async def fetchone(self) -> Any: ...
    async def fetchall(self) -> list[Any]: ...


class Connection(Protocol):
    row_factory: Any

    async def __aenter__(self) -> Connection: ...
    async def __aexit__(self, exc_type: Any, exc: Any, tb: Any) -> None: ...
    async def execute(self, sql: str, parameters: Iterable[Any] | None = ...) -> Cursor: ...
    async def executescript(self, sql_script: str) -> None: ...
    async def execute_fetchall(self, sql: str, parameters: Iterable[Any] | None = ...) -> list[Any]: ...
    async def commit(self) -> None: ...


def connect(database: str, *args: Any, **kwargs: Any) -> Connection: ...
