"""Slash commands — workflow group."""
from __future__ import annotations

import os
import shlex
import subprocess
from typing import TYPE_CHECKING

from ._registry import slash_command, TRIGGER_AGENT, TRIGGER_AGENT_SINGLE

if TYPE_CHECKING:
    from ..loop import AgentLoop

@slash_command("vim", "Open a file in vim/nano editor")
def cmd_vim(agent: AgentLoop, args: str) -> str:
    if not args.strip():
        return "Usage: /vim <filepath>"
    filepath = args.strip()
    editor = os.environ.get("EDITOR", "vim")
    try:
        editor_argv = shlex.split(editor)
    except ValueError as exc:
        return f"Invalid EDITOR value: {exc}"
    if not editor_argv:
        return "Invalid EDITOR value: empty command"
    subprocess.run([*editor_argv, filepath], check=False)
    return f"Opened {filepath} in {editor}"


@slash_command("interview", "Start a deep interview to clarify requirements")
def cmd_interview(agent: AgentLoop, args: str) -> str:
    from ..interview import DeepInterviewer, load_latest_interview

    if not args.strip():
        # Try to resume a previous interview
        state = load_latest_interview()
        if state and not state.is_complete:
            interviewer = DeepInterviewer(agent.llm, agent.cwd)
            question = interviewer.generate_question(state)
            progress = interviewer.format_progress(state)
            return f"Resuming interview ({state.interview_id})\n{progress}\n\nNext question:\n{question}"
        return "Usage: /interview <your idea or description>\nStarts a Socratic deep interview to clarify requirements before execution."

    idea = args.strip()
    from ..interview import DeepInterviewer as _DI

    interviewer = _DI(agent.llm, agent.cwd)
    state = interviewer.start(idea)

    # First question is generated by the LLM agent via streaming (non-streaming call removed to prevent timeout)
    agent.messages.append(
        {
            "role": "user",
            "content": (
                f"You are conducting a deep interview to clarify requirements.\n"
                f'User\'s idea: "{idea}"\n'
                f"Project type: {state.project_type.value}\n"
                f"Interview ID: {state.interview_id}\n\n"
                "Start by asking the FIRST targeted question to clarify the user's requirements.\n"
                "Rules:\n"
                "1. Ask ONE question at a time — focus on the weakest clarity dimension\n"
                "2. Show ambiguity score after each answer (Goal/Constraints/Criteria 0-100%)\n"
                "3. Round 4+: challenge assumptions. Round 6+: simplify. Round 8+: find essence.\n"
                "4. When ambiguity ≤ 20%, generate a spec and offer execution options.\n\n"
                "Now ask your first question."
            ),
        }
    )
    return TRIGGER_AGENT_SINGLE


@slash_command("think", "Send a question to LLM for pure reasoning (no tools)")
def cmd_think(agent: AgentLoop, args: str) -> str:
    question = args.strip()
    if not question:
        return "Usage: /think <question>"
    try:
        response = agent.llm.chat(
            messages=[{"role": "user", "content": question}],
            system="You are a thoughtful reasoning assistant. Think carefully and thoroughly. No tool calls — pure reasoning only.",
            temperature=0.7,
        )
        return response.content or "[No response]"
    except Exception as e:
        return f"Error: {e}"


@slash_command("ralph", "Start persistence loop — keeps working until task is done")
def cmd_ralph(agent: AgentLoop, args: str) -> str:
    if not args.strip():
        return "Usage: /ralph <task description>"

    agent._ran_ralph = True  # Enable keep-going resume flag
    from ..ralph import Ralph, save_state

    # Auto model routing: switch to speed model (long code generation)
    prev_model = agent.llm.use_tier("speed")
    agent.emitter.model_changed(prev_model, agent.llm.model)

    ralph = Ralph(llm=agent.llm, tools=list(agent.tools.values()), cwd=agent.cwd, emitter=agent.emitter)
    setattr(ralph, "_parent_agent", agent)  # btw: for receiving user messages during execution
    state = ralph.start(args.strip())
    save_state(state)

    agent.messages.append(
        {
            "role": "user",
            "content": (
                f"[Ralph] Starting persistence loop for task: {args.strip()}\n"
                f"Task ID: {state.task_id}\n"
                f"Acceptance criteria ({len(state.acceptance_criteria)}):\n"
                + "\n".join(f"  {i + 1}. {c}" for i, c in enumerate(state.acceptance_criteria))
                + f"\n\nRunning up to {state.max_iterations} iterations until all criteria are met."
            ),
        }
    )

    # Run the loop synchronously (blocking)
    try:
        summary = ralph.run_loop(state)
    finally:
        agent.llm.restore_model(prev_model)
        agent.emitter.model_changed(agent.llm.model, prev_model)

    return f"[Ralph completed]\n{summary}"


@slash_command("cancel", "Cancel active execution mode (ralph, ultraqa, etc)")
def cmd_cancel(agent: AgentLoop, args: str) -> str:
    cancelled = []
    from ..ralph import find_active_ralph
    from ..ralph import save_state as ralph_save

    rs = find_active_ralph()
    if rs:
        rs.status = "cancelled"
        ralph_save(rs)
        cancelled.append(f"Ralph [{rs.task_id}]")
    from ..autopilot import _save as ap_save
    from ..autopilot import find_active_autopilot

    ap = find_active_autopilot()
    if ap:
        ap.status = "cancelled"
        ap.phase_log.append("cancelled")
        ap_save(ap)
        cancelled.append(f"Autopilot [{ap.task_id}] at phase {ap.phase.value}")
    try:
        from ..ultraqa import find_active_ultraqa
        from ..ultraqa import save_state as uqa_save

        uq = find_active_ultraqa()
        if uq:
            uq.status = "cancelled"
            uqa_save(uq)
            cancelled.append(f"UltraQA [{uq.task_id}]")
    except Exception:
        pass
    if cancelled:
        return "Cancelled:\n" + "\n".join(f"  - {c}" for c in cancelled)
    return "No active execution modes found."


@slash_command("autopilot", "Full autonomous pipeline — spec→plan→execute→QA→verify")
def cmd_autopilot(agent: AgentLoop, args: str) -> str:
    if not args.strip():
        return "Usage: /autopilot <task description>"
    from ..autopilot import Autopilot

    prev_model = agent.llm.use_tier("speed")
    agent.emitter.model_changed(prev_model, agent.llm.model)

    ap = Autopilot(agent.llm, agent.cwd, emitter=agent.emitter)
    state = ap.start(args.strip())
    try:
        summary = ap.run(state)
    finally:
        agent.llm.restore_model(prev_model)
        agent.emitter.model_changed(agent.llm.model, prev_model)

    return f"[Autopilot completed]\n{summary}"


@slash_command("mcp", "Show MCP server status")
def cmd_mcp(agent: AgentLoop, args: str) -> str:
    try:
        from ..mcp import MCPManager

        mcp = MCPManager()
        servers = mcp.status()
        if not servers:
            return (
                "No MCP servers configured.\n"
                "Edit ~/.hermit/mcp.json to add servers.\n\n"
                'Example:\n  {"servers": {"filesystem": {"command": "npx", "args": ["-y", "@modelcontextprotocol/server-filesystem", "/tmp"]}}}'
            )
        lines = ["MCP Servers:"]
        for s in servers:
            status = "[connected]" if s["connected"] else "[disconnected]"
            lines.append(f"  {status} {s['name']} — {s['command']} ({s['tools']} tools)")
        return "\n".join(lines)
    except Exception as e:
        return f"MCP error: {e}"


@slash_command("ultraqa", "Start QA cycling — test→diagnose→fix→repeat until pass")
def cmd_ultraqa(agent: AgentLoop, args: str) -> str:
    from ..ultraqa import UltraQA

    test_command = args.strip() or None
    qa = UltraQA(llm=agent.llm, tools=list(agent.tools.values()), cwd=agent.cwd, emitter=agent.emitter)
    state = qa.start(test_command)

    agent.emitter.progress(f"[UltraQA] Starting — command: {state.test_command} | max cycles: {state.max_cycles}")

    summary = qa.run_loop(state)

    return f"[UltraQA completed]\n{summary}"


@slash_command("consensus", "Run consensus planning (Planner→Architect→Critic)")
def cmd_consensus(agent: AgentLoop, args: str) -> str:
    task = args.strip()
    if not task:
        return "Usage: /consensus <task description>"

    from ..auto_agents import run_plan_consensus

    agent.emitter.progress(f"[Consensus] Starting for: {task[:60]}")
    result = run_plan_consensus(llm=agent.llm, cwd=agent.cwd, task=task)

    return f"[Consensus plan ready]\n{result}"


@slash_command("learn", "Show agent-learner v2 guidance; learning now runs on session stop.")
def cmd_learn(agent: AgentLoop, args: str) -> str:
    requested = args.strip()
    if requested == "status":
        return "Learning is handled by agent-learner v2. Run: hermit_agent learner status"
    if requested == "reset":
        return "Learning is handled by agent-learner v2. Use agent-learner review/cleanup commands instead of /learn reset."
    return (
        "Learning is handled by agent-learner v2 on session stop. "
        "Use `hermit_agent learner status` to inspect learned rules."
    )


@slash_command("team", "Run tasks with coordinated parallel agents")
def cmd_team(agent: AgentLoop, args: str) -> str:
    if not args.strip():
        return "Usage: /team <task1> && <task2> && ..."
    tasks = [t.strip() for t in args.split("&&") if t.strip()]
    if len(tasks) < 2:
        return "Need at least 2 tasks separated by &&"

    from ..coordinator import run_parallel_agents

    task_dicts = [{"description": f"Task {i + 1}", "prompt": t} for i, t in enumerate(tasks)]
    result = run_parallel_agents(task_dicts, agent.llm, agent.cwd)
    return f"[Team completed]\n{result.summary}"


@slash_command("research", "Deep research — search multiple sources and cross-verify")
def cmd_research(agent: AgentLoop, args: str) -> str:
    if not args.strip():
        return "Usage: /research <topic>"
    # Use deep_search tool via agent
    agent.messages.append(
        {
            "role": "user",
            "content": f"Research this topic thoroughly using deep_search. Search for multiple perspectives, cross-verify facts, and cite sources:\n\n{args.strip()}",
        }
    )
    return TRIGGER_AGENT


@slash_command("hud", "Configure status bar display")
def cmd_hud(agent: AgentLoop, args: str) -> str:
    if not args.strip():
        return "HUD presets:\n  /hud minimal — model + ctx only\n  /hud full — all info\n  /hud off — hide status bar"
    preset = args.strip().lower()
    # Store preference in memory
    from ..memory import MemorySystem

    mem = MemorySystem()
    mem.save("hud_preset", f"HUD preset: {preset}", "feedback", f"User prefers {preset} HUD")
    return f"HUD preset set to: {preset} (applied next session)"
